site_name: 'Developer Portal Getting Started'
repo_url: https://github.com/modern-engineering-platform/developer-portal
edit_uri: edit/master/documentation/docs

nav:
  - Home: index.md
  - 'Using your repositories': using-your-repositories.md
  - 'Enabled Plugins': enabled-plugins.md

plugins:
  - techdocs-core
